# Generated by Django 5.0.2 on 2025-04-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancelog",
            name="status",
            field=models.CharField(default="in", max_length=10),
        ),
    ]
