# Generated by Django 5.0.2 on 2025-04-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendancelog_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancelog",
            name="status",
        ),
    ]
